name: attendance_management_system
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  http: ^1.1.2
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
flutter_icons:
  android: true
  ios: true 
  image_path: assets/icon/applogo.png


flutter:

 
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icon/

  